apiVersion: v1
kind: Pod
metadata:
  name: pod-blue
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: simple-webapp-color-blue
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue
